openapi: 3.0.0
info:
  title: AI Chat Agent API
  description: API for interacting with the AI chat agent for task management
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.taskflow.com
    description: Production server

paths:
  /api/chat:
    post:
      summary: Send a message to the AI chat agent
      description: Sends a user message to the AI agent and receives a response. Creates or continues a conversation.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: The user's message to the AI agent
                  example: "Add a task to buy groceries"
                conversation_id:
                  type: string
                  format: uuid
                  description: Optional conversation ID to continue an existing conversation
                  example: "123e4567-e89b-12d3-a456-426614174000"
              required:
                - message
      responses:
        '200':
          description: Successful response from the AI agent
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    description: The AI agent's response to the user
                    example: "I've added the task 'buy groceries' to your list."
                  conversation_id:
                    type: string
                    format: uuid
                    description: The ID of the conversation
                    example: "123e4567-e89b-12d3-a456-426614174000"
                  message_id:
                    type: string
                    format: uuid
                    description: The ID of the response message
                    example: "987e6543-d21c-ba98-7654-0987654321ff"
                  tool_calls:
                    type: array
                    items:
                      type: object
                      properties:
                        tool_name:
                          type: string
                          description: The name of the tool called
                        parameters:
                          type: object
                          description: Parameters passed to the tool
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/conversations:
    get:
      summary: Get user's conversations
      description: Retrieve a list of conversations for the authenticated user
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of user's conversations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ConversationSummary'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/conversations/{conversation_id}:
    get:
      summary: Get conversation details
      description: Retrieve details of a specific conversation
      security:
        - BearerAuth: []
      parameters:
        - name: conversation_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Conversation details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationDetail'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/conversations/{conversation_id}/messages:
    get:
      summary: Get conversation messages
      description: Retrieve messages from a specific conversation
      security:
        - BearerAuth: []
      parameters:
        - name: conversation_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
          description: Maximum number of messages to return
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
          description: Number of messages to skip
      responses:
        '200':
          description: List of messages in the conversation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ConversationSummary:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the conversation
        title:
          type: string
          description: Summary title of the conversation
        created_at:
          type: string
          format: date-time
          description: When the conversation was created
        updated_at:
          type: string
          format: date-time
          description: When the conversation was last updated
      required:
        - id
        - title
        - created_at
        - updated_at

    ConversationDetail:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the conversation
        user_id:
          type: string
          format: uuid
          description: ID of the user who owns this conversation
        title:
          type: string
          description: Summary title of the conversation
        created_at:
          type: string
          format: date-time
          description: When the conversation was created
        updated_at:
          type: string
          format: date-time
          description: When the conversation was last updated
      required:
        - id
        - user_id
        - title
        - created_at
        - updated_at

    Message:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the message
        conversation_id:
          type: string
          format: uuid
          description: ID of the conversation this message belongs to
        user_id:
          type: string
          format: uuid
          description: ID of the user who sent this message
        role:
          type: string
          enum: [user, assistant]
          description: Role of the message sender
        content:
          type: string
          description: Content of the message
        timestamp:
          type: string
          format: date-time
          description: When the message was sent
        metadata:
          type: object
          description: Additional metadata about the message
          nullable: true
      required:
        - id
        - conversation_id
        - user_id
        - role
        - content
        - timestamp

  responses:
    BadRequest:
      description: Bad request - invalid input
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
                description: Error details
            example:
              detail: "Invalid input data"

    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
                description: Error details
            example:
              detail: "Not authenticated"

    Forbidden:
      description: Insufficient permissions
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
                description: Error details
            example:
              detail: "Access denied"

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
                description: Error details
            example:
              detail: "Conversation not found"

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
                description: Error details
            example:
              detail: "An internal error occurred"